---
title: "Validation CA positions"
date: "`r format(Sys.time(), '%d %B %Y, %H:%M')`"
output:
  html_notebook:
    code_folding: hide
    toc: yes
    toc_float: yes
---
<style type="text/css"> <!-- .table { width: auto } ---> </style>
---

```{r options, include=FALSE}
knitr::opts_chunk$set(
  # results = "hide",
  message = FALSE,
  warning = FALSE,
  package.startup.message = FALSE
  )

options(
  knitr.kable.NA = "",
  readr.num_columns = 0,
  width = 100
)
```

```{r sources, message=FALSE}
library(tidyverse)

wp_raw <- read_csv("../04-data-final/party-position-tags.csv")
pp_raw <- read_csv("../01-data-sources/03-party-positions/02-party-positions.csv")

load("../03-estimation/estimation-model/01-data-m2.RData")

file_wikipedia <- "../01-data-sources/02-wikipedia/wikipedia-data/01-wp-data-json.zip"
file_wikipedia_date <- substr(file.info(file_wikipedia)$mtime, 1, 10)

file_estimation <- "../03-estimation/estimation-model/02-stan-samples-2d-m2_1.csv"
file_estimation_date <- substr(file.info(file_estimation)$mtime, 1, 10)
```


Correspondence analysis (CA) data information

+ Wikipedia data download -- `r file_wikipedia_date`
+ CA estimation -- `r file_estimation_date`
+ [ date file modified ]

Data used for validation

+ CHES -- Chapel Hill Expert Survey


```{r data}
if (ca$cscore["conservatism", 1] < 0)
  x_init_1 <- -x_init_1

if (ca$cscore["euroscepticism", 2] > 0)
  x_init_2 <- -x_init_2

ca_raw <- tibble(partyfacts_id, dimension_1 = x_init_1, dimension_2 = x_init_2)

pp_long <-
  pp_raw %>%
  select(country, where(is.numeric)) %>%
  pivot_longer(
    cols = c(-country, -partyfacts_id),
    names_to = "variable",
    values_to = "position",
    values_drop_na = TRUE
    ) %>%
  filter(! str_detect(variable, "_id$"))

dt <-
  pp_long %>%
  left_join(ca_raw, by = "partyfacts_id") %>%
  mutate(
    dataset = str_remove_all(variable, "_.*") %>% str_to_upper(),
    variable = str_remove(variable, "^.*?_"),
    ) %>%
  na.omit()

pp_all <-
  ca_raw %>%
  left_join(pp_raw, by = "partyfacts_id")
```


## Left-right

```{r ca-lr-graph, message=FALSE}
pl_dt <-
  dt %>%
  filter(variable == "left_right") %>%
  select(dataset, left_right = position, dim_1_ca = dimension_1)

pl_lr_ca <- ggplot(pl_dt, aes(x = left_right, y = dim_1_ca)) +
  geom_smooth(method = lm, se = FALSE) +
  geom_point(alpha = 0.3)

print(pl_lr_ca)
```


## EU integration

```{r ca-eu-graph, message=FALSE}
pl_dt <-
  dt %>%
  filter(variable == "eu_integration") %>%
  select(dataset, eu_integration = position, dim_2_ca = dimension_2)

pl_eu_ca <- ggplot(pl_dt, aes(x = eu_integration, y = dim_2_ca)) +
  geom_smooth(method = lm, se = FALSE) +
  geom_point(alpha = 0.3)

print(pl_eu_ca)
```


## First dimension

```{r}
dt %>%
  group_by(dataset, variable) %>%
  summarise(
    correlation = round(cor(position, dimension_1, use = "na.or.complete"), 2),
    .groups = "drop"
    ) %>%
  arrange(desc(abs(correlation))) %>%
  knitr::kable()
```



## Second dimension

```{r}
dt %>%
  group_by(dataset, variable) %>%
  summarise(
    correlation = round(cor(position, dimension_2, use = "na.or.complete"), 2),
    .groups = "drop"
    ) %>%
  arrange(desc(abs(correlation))) %>%
  knitr::kable()
```



## First vs. second

```{r, rows.print = 4}
tibble(
  dimensions = "left-right vs. EU integration",
  CHES = round(
    cor(pp_all$ches_left_right, pp_all$ches_eu_integration, use = "na.or.complete"),
    2
  ),
  CA = round(
    cor(pp_all$dimension_1, pp_all$dimension_2, use = "na.or.complete"),
    2
  ),
) %>% knitr::kable()
```



## CHES positions

```{r ches-positions-graph, message=FALSE}
pl_dt <-
  pp_raw %>%
  select(left_right = ches_left_right, eu_integration = ches_eu_integration)

pl_2d_ches <- ggplot(pl_dt, aes(x = left_right, y = eu_integration)) +
  geom_point(alpha = 0.3)

print(pl_2d_ches)
```


## CA scores

```{r wp-positions-graph, message = FALSE}
ab_wp <- cbind(
  coef(lm(ches_left_right ~ dimension_1 + dimension_2, data = pp_all)),
  coef(lm(ches_eu_integration ~ dimension_1 + dimension_2, data = pp_all))
)[paste0("dimension_", 1:2), ]

pl_dt <-
  ca_raw %>%
  select(dim_1_left_right = dimension_1, dim_2_eu_integration = dimension_2)

pl_2d_ca <- ggplot(
  pl_dt,
  aes(x = dim_1_left_right, y = dim_2_eu_integration)
) +
  geom_abline(
    slope = ab_wp["dimension_2", 1] / ab_wp["dimension_1", 1],
    intercept = 0,
    colour = "red",
    alpha = 0.5
) +
  geom_abline(
    slope = ab_wp["dimension_2", 2] / ab_wp["dimension_1", 2],
    intercept = 0,
    colour = "blue",
    alpha = 0.5
) +
  geom_point(alpha = 0.3)

print(pl_2d_ca)
```